import type { IContent } from '@/types/content'

export const iconsLinks: IContent[] = [
  {
    name: 'Shapes',
    description: 'Copy-Paste SVG Shapes',
    url: 'https://shapes.framer.website/',
    image: '/images/icons/shapes.webp',
    optional: 'free',
    isNew: true,
  },
  {
    name: 'Notioly',
    description: 'Beautiful Notion-style illustrations',
    url: 'https://notioly.com/',
    image: '/images/icons/notioly.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'Fffuel',
    description: 'A collection of color tools and free SVG generators for gradients, patterns, textures, shapes & backgrounds',
    url: 'https://www.fffuel.co/',
    image: '/images/icons/fffuel.webp',
    optional: 'free',
    isNew: true,
  },
  {
    name: 'Nucleo',
    description: 'Use Nucleo to organize, customize, and share all your icons',
    url: 'https://nucleoapp.com/',
    image: '/images/icons/nucleoapp.webp',
    optional: 'free & paid',
    whiteBg: true,
  },
  {
    name: 'wannathis',
    description: 'design products, to work easier',
    url: 'https://wannathis.one/',
    image: '/images/icons/wannathis.webp',
    optional: 'paid',
  },
  {
    name: 'looneypatterns',
    description: '45 cool seamless hand-drawn vector patterns',
    url: 'https://looneypatterns.com/',
    image: '/images/icons/looneypatterns.webp',
    optional: 'paid',
  },
  {
    name: 'Сoolshapes',
    description: '100+ custom shapes',
    url: 'https://coolshap.es/',
    image: '/images/icons/coolshapes.webp',
    optional: 'free',
  },
  {
    name: 'icons.pqoqubbw',
    description: 'beautifully crafted animated icons',
    url: 'https://icons.pqoqubbw.dev/',
    image: '/images/icons/pqoqubbw.webp',
    optional: 'free',
  },
  {
    name: 'feathericons',
    description: 'simply beautiful open source icons',
    url: 'https://feathericons.com/',
    image: '/images/icons/feathericons.webp',
    optional: 'free',
  },
  {
    name: 'thenounproject',
    description: 'free icons and stock photos for everything',
    url: 'https://thenounproject.com/',
    image: '/images/icons/thenounproject.webp',
    optional: 'free',
  },
  {
    name: 'phosphoricons',
    description: 'a flexible icon family for interfaces, diagrams, presentations',
    url: 'https://phosphoricons.com/',
    image: '/images/icons/phosphoricons.webp',
    optional: 'free',
  },
]
