import type { IContent } from '@/types/content'

export const mockupsLinks: IContent[] = [
  {
    name: 'Shots',
    description: 'Create amazing mockups',
    url: 'https://shots.so/',
    image: '/images/mockups/shots.webp',
    optional: 'free',
  },
  {
    name: 'Previewed',
    description: 'Mockup generator for your app',
    url: 'https://previewed.app/',
    image: '/images/mockups/previewed.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'Morflax',
    description: 'Generate 3D device mockup in a quick and engaging way',
    url: 'https://things.morflax.com/',
    image: '/images/mockups/morflax.webp',
    optional: 'free & paid',
    whiteBg: true,
  },
  {
    name: 'MockUPhone',
    description: 'Free and Simple Screenshots Device Mockups Generator',
    url: 'https://mockuphone.com/',
    image: '/images/mockups/mockuphone.webp',
    optional: 'free',
    whiteBg: true,
  },
  {
    name: 'ls.graphics',
    description: 'A wide range of mockups for devices, branding, and packaging',
    url: 'https://www.ls.graphics/',
    image: '/images/mockups/ls_graphics.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'wannathis',
    description: ' high-quality mockups, perfect for showcasing digital designs with style',
    url: 'https://wannathis.one/mockups',
    image: '/images/mockups/wannathis.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'the-brandidentity',
    description: 'templates, assets, ebooks',
    url: 'https://the-brandidentity.com',
    image: '/images/mockups/brandidentity.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'https://artdirected.design/',
    description: 'realistic mockups for every scenario',
    url: 'https://artdirected.design/',
    image: '/images/mockups/artdirected.webp',
    optional: 'paid',
    whiteBg: true,
  },
]
