import type { IContent } from '@/types/content'

export const typographyLinks: IContent[] = [
  {
    name: 'Fontshare',
    description: 'Free font',
    url: 'https://www.fontshare.com/',
    image: '/images/typography/fontshare.webp',
    optional: 'free',
    isNew: true,
  },
  {
    name: 'Freefaces',
    description: 'Free nice fonts',
    url: 'https://www.freefaces.gallery/',
    image: '/images/typography/freefaces.webp',
    optional: 'free',
  },
  {
    name: 'Uncut',
    description: 'Free beatiful fonts',
    url: 'https://uncut.wtf/',
    image: '/images/typography/uncut.webp',
    optional: 'free',
  },
  {
    name: 'Good Type Foundry',
    description: 'Collection of good paid fonts',
    url: 'https://goodtypefoundry.com/',
    image: '/images/typography/goodtypefoundry.webp',
    optional: 'paid',
  },
  {
    name: 'SN Pro',
    description: 'Free typeface fron Super Notes',
    url: 'https://supernotes.app/open-source/sn-pro/',
    image: '/images/typography/sn-pro.webp',
    optional: 'free',
    whiteBg: true,
  },
  {
    name: 'Geist',
    description: 'Inter alternative from Vercel',
    url: 'https://vercel.com/font',
    image: '/images/typography/geist.png',
    optional: 'free',
  },
  {
    name: 'Faire type foundry',
    description: 'Faire type',
    url: 'https://www.fairetype.com/fonts',
    image: '/images/typography/fairetype.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'Groteskly Yours Studio Fonts',
    description: 'a library of modern retail fonts for branding, web, and design projects.',
    url: 'https://groteskly.xyz/fonts',
    image: '/images/typography/groteskly.webp',
    optional: 'paid',
  },
  {
    name: 'contrastfoundry',
    description: 'CoFo is a typeface design studio based in the San Francisco Bay Area focused on letterforms',
    url: 'https://contrastfoundry.com/',
    image: '/images/typography/contrastfoundry.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'departuremono',
    description: 'departure mono is a monospaced pixel font with a lo-fi technical vibe',
    url: 'https://departuremono.com/',
    image: '/images/typography/departuremono.webp',
    optional: 'free',
  },
  {
    name: 'pangrampangram',
    description: 'free to try, High-Quality Fonts for Designers',
    url: 'https://pangrampangram.com/',
    image: '/images/typography/pangrampangram.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'cotypefoundry',
    description: 'small collection of co type foundy fonts',
    url: 'https://cotypefoundry.com/',
    image: '/images/typography/cotypefoundry.webp',
    optional: 'paid',
    whiteBg: true,
  },
  {
    name: 'typotheque',
    description: 'collection of unique designed typefonts',
    url: 'https://typotheque.le75.be/',
    image: '/images/typography/typotheque.webp',
    optional: 'paid',
    whiteBg: true,
  },
]
